apiVersion: v1
kind: Service
metadata:
  name: reports
spec:
  selector:
    app: reports
  ports:
    - protocol: TCP
      port: 8051
      targetPort: 8051
      nodePort: 32080  # or any port between 30000–32767
  type: NodePort