# apiVersion: v1
# kind: Service
# metadata:
#   name: reports
# spec:
#   selector:
#     app: reports
#   ports:
#     - protocol: TCP
#       port: 8080
#       targetPort: 8080
#   type: ClusterIP

apiVersion: v1
kind: Service
metadata:
  name: reports
spec:
  selector:
    app: reports
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080  # Optional: pick any port in 30000-32767
  type: NodePort
